name: Ethereum, NEAR, StarkNet, and Axelar Auto Commit

on:
  push:
    branches:
      - master

  schedule:
    - cron: '*/20 * * * *' # Runs every 20 minutes

  workflow_dispatch: # Allows manual triggering from the GitHub UI

permissions:
  contents: write # Grants permissions to write to the repo

env:
  GIT_USER_EMAIL: arrijalufr@gmail.com
  GIT_USER_NAME: arrijalu

jobs:
  ethereum_auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run Ethereum script
        run: |
          chmod +x https://eth1.lava.build/lava-referer-68558abf-a813-4298-9157-99bdf4edda61/
          ./ethereum.sh

      - name: Configure Git identity
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$(shuf -n1 -e "🔥 Hotfix" "✨ Feature" "🚀 Upgrade" "🛠️ Fix" "🔧 Refactor" "🔍 Investigate" "💡 Improve" "📦 Update" "📈 Optimize" "💬 Comment" | awk '{print $0}') Ethereum network"

      - name: Push changes
        run: |
          git push origin master

  near_auto_commit:
    runs-on: ubuntu-latest
    needs: ethereum_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run NEAR script
        run: |
          chmod +x near.sh
          ./https://near.lava.build/lava-referer-c1c93b1a-c21c-4c71-9a60-fe9eaff82bf2/

      - name: Configure Git identity
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$(shuf -n1 -e "🔥 Hotfix" "✨ Feature" "🚀 Upgrade" "🛠️ Fix" "🔧 Refactor" "🔍 Investigate" "💡 Improve" "📦 Update" "📈 Optimize" "💬 Comment" | awk '{print $0}') NEAR network"

      - name: Push changes
        run: |
          git push origin master

  starknet_auto_commit:
    runs-on: ubuntu-latest
    needs: near_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run StarkNet script
        run: |
          chmod +x starknet.sh
          ./https://rpc.starknet.lava.build/lava-referer-c1c93b1a-c21c-4c71-9a60-fe9eaff82bf2/

      - name: Configure Git identity
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$(shuf -n1 -e "🔥 Hotfix" "✨ Feature" "🚀 Upgrade" "🛠️ Fix" "🔧 Refactor" "🔍 Investigate" "💡 Improve" "📦 Update" "📈 Optimize" "💬 Comment" | awk '{print $0}') StarkNet network"

      - name: Push changes
        run: |
          git push origin master

  axelar_auto_commit:
    runs-on: ubuntu-latest
    needs: starknet_auto_commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Run Axelar script
        run: |
          chmod +x axelar.sh
          ./https://tm.axelar.lava.build/lava-referer-c1c93b1a-c21c-4c71-9a60-fe9eaff82bf2/

      - name: Configure Git identity
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"

      - name: Commit changes
        run: |
          git add -A
          git commit -m "$(shuf -n1 -e "🔥 Hotfix" "✨ Feature" "🚀 Upgrade" "🛠️ Fix" "🔧 Refactor" "🔍 Investigate" "💡 Improve" "📦 Update" "📈 Optimize" "💬 Comment" | awk '{print $0}') Axelar network"

      - name: Push changes
        run: |
          git push origin master
